version: '3'
services:
    nginx:
        image: nginx
        networks:
            magnum_net:
                ipv4_address: 172.1.32.6
        volumes:
            - ./nginx/config/site.dev.conf:/etc/nginx/conf.d/site.dev.conf
            - ./nginx/config/site.prod.conf:/etc/nginx/conf.d/site.prod.conf
            - ./nginx/logs:/var/log/nginx
            - ${HOST_DOCROOT}:/home/app/docroot
        ports:
            - ${HOST_PORT_DEV}:8800
            - ${HOST_PORT_PROD}:8801
    php-71:
        image: pelso/php${IB_DOCKER_PHP}:7.1
        hostname: dev-magnum-php-71
        tty: true
        volumes:
            - ${HOST_DOCROOT}:/home/app/docroot
            - ./php/config/fpm_php.ini:/etc/php/7.1/fpm/php.ini
            - ./php/config/cli_php.ini:/etc/php/7.1/cli/php.ini
        networks:
            magnum_net:
              ipv4_address: 172.1.32.2
    db:
        image: percona/percona-server:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/config/my.cnf:/etc/mysql/my.cnf
            - ./mysql/data:/var/lib/mysql
            - ./mysql/logs:/var/log/mysql
        ports:
            - ${HOST_PORT_DB}:3306
        networks:
            magnum_net:
                ipv4_address: 172.1.32.3
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${HOST_PORT_PMA}:80
        environment:
            - PMA_HOST=172.1.32.3
        networks:
            magnum_net:
                ipv4_address: 172.1.32.7

networks:
    magnum_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.32.0/24