version: '3'
services:
    nginx:
        image: nginx
        networks:
            evista_net:
                ipv4_address: 172.1.64.2
        volumes:
            - ./nginx/config/site.dev.conf:/etc/nginx/conf.d/site.dev.conf
            - ./nginx/config/site.prod.conf:/etc/nginx/conf.d/site.prod.conf
            - ./nginx/logs:/var/log/nginx
            - ${BACKEND_DOCROOT}:/home/app/docroot
        ports:
            - ${HOST_PORT_DEV}:8800
            - ${HOST_PORT_PROD}:8801
    php-73:
        image: pelso/php${IB_DOCKER_PHP}:7.3
        hostname: dev-evista_backend-php-73
        tty: true
        volumes:
            - ${BACKEND_DOCROOT}:/home/app/docroot
            - ./php/config/fpm_php.ini:/etc/php/7.3/fpm/php.ini
            - ./php/config/cli_php.ini:/etc/php/7.3/cli/php.ini
        networks:
            evista_net:
                ipv4_address: 172.1.64.3
    db:
        image: percona/percona-server:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/config/my.cnf:/etc/mysql/my.cnf
        ports:
            - ${HOST_PORT_DB}:3306
        networks:
            evista_net:
                ipv4_address: 172.1.64.4
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${HOST_PORT_PMA}:80
        environment:
            - PMA_HOST=172.1.64.4
        networks:
            evista_net:
                ipv4_address: 172.1.64.5
networks:
    evista_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.64.0/24